#!/usr/bin/env bash
#
# Complete OS Anti-Filtering Optimization Script
# Author Telegram : @ScriptingGs
# GitHub          : https://github.com/samanamwowo/
#
# Supported distros: Ubuntu 20.04 / 22.04 / 24.04, Debian 11 / 12
#
set -uo pipefail

# ============================================================
#  Colors / Style
# ============================================================
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
MAGENTA='\033[0;35m'
BOLD='\033[1m'
NC='\033[0m'

SYSCTL_FILE="/etc/sysctl.d/99-antidpi.conf"
NIC_SERVICE="/etc/systemd/system/antidpi-nic.service"
NGINX_CONF="/etc/nginx/conf.d/antidpi.conf"
GLOBAL_CMD_A="/usr/local/bin/anti-dpi"
GLOBAL_CMD_B="/usr/bin/anti-dpi"
SELF_PATH="$(readlink -f "$0")"
STATE_DIR="/etc/antidpi"
STATE_IFACE_FILE="${STATE_DIR}/iface"

log_info()  { echo -e "${CYAN}[INFO]${NC}  $1"; }
log_ok()    { echo -e "${GREEN}[ OK ]${NC}  $1"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC}  $1"; }
log_err()   { echo -e "${RED}[FAIL]${NC}  $1"; }
log_step()  { echo -e "${MAGENTA}[STEP]${NC} ${BOLD}$1${NC}"; }

# ============================================================
#  Banner
# ============================================================
print_banner() {
    clear
    echo -e "${CYAN}${BOLD}"
    cat << "EOF"
    ___          __  _        ____  ____ ____
   /   |  ____  / /_(_)      / __ \/ __ \  _/
  / /| | / __ \/ __/ /______/ / / / /_/ /_ \
 / ___ |/ / / / /_/ /_____/ /_/ / ____/__/ /
/_/  |_/_/ /_/\__/_/      \____/_/   /____/

EOF
    echo -e "${NC}"
    echo -e "${BOLD}  Project   :${NC} Complete OS Anti-Filtering Optimization"
    echo -e "${BOLD}  Telegram  :${NC} ${GREEN}@ScriptingGs${NC}"
    echo -e "${BOLD}  GitHub    :${NC} ${GREEN}https://github.com/samanamwowo/${NC}"
    echo -e "${BLUE}------------------------------------------------------------${NC}"
}

# ============================================================
#  Root check
# ============================================================
check_root() {
    if [[ $EUID -ne 0 ]]; then
        log_err "This script must be run as root. Try: sudo bash $0"
        exit 1
    fi
}

# ============================================================
#  Detect primary network interface
# ============================================================
detect_iface() {
    local iface
    iface=$(ip route get 8.8.8.8 2>/dev/null | awk '/dev/ {for(i=1;i<=NF;i++) if ($i=="dev") print $(i+1)}' | head -n1)
    if [[ -z "$iface" ]]; then
        iface=$(ip -o -4 route show to default 2>/dev/null | awk '{print $5}' | head -n1)
    fi
    if [[ -z "$iface" ]]; then
        log_err "Could not auto-detect the primary network interface."
        exit 1
    fi
    echo "$iface"
}

# ============================================================
#  Install self as global command
# ============================================================
install_global_command() {
    log_step "Installing global command 'anti-dpi'..."
    local target="$GLOBAL_CMD_A"
    mkdir -p "$(dirname "$target")" 2>/dev/null || target="$GLOBAL_CMD_B"

    if [[ "$SELF_PATH" != "$target" ]]; then
        cp -f "$SELF_PATH" "$target"
        chmod +x "$target"
    else
        chmod +x "$target"
    fi

    if command -v anti-dpi >/dev/null 2>&1; then
        log_ok "You can now run this tool anywhere by typing: anti-dpi"
    else
        log_warn "Installed to $target but it is not yet on PATH in this shell. Try opening a new terminal."
    fi
}

# ============================================================
#  1) Kernel sysctl tweaks
# ============================================================
apply_kernel_tweaks() {
    log_step "Applying kernel network stack tweaks..."
    mkdir -p "$(dirname "$SYSCTL_FILE")"

    cat > "$SYSCTL_FILE" << 'SYSCTL_EOF'
# Generated by Complete OS Anti-Filtering Optimization Script
# Do not edit manually - regenerate via 'anti-dpi'

# --- BBR + fq for better throughput / congestion behaviour ---
net.core.default_qdisc = fq
net.ipv4.tcp_congestion_control = bbr

# --- Reduce OS/network fingerprinting surface ---
net.ipv4.tcp_timestamps = 0
net.ipv4.ip_default_ttl = 128

# --- TCP Fast Open ---
net.ipv4.tcp_fastopen = 3

# --- Buffer / receive window tuning ---
net.ipv4.tcp_rmem = 4096 87380 67108864
net.ipv4.tcp_wmem = 4096 65536 67108864
net.ipv4.tcp_moderate_rcvbuf = 1
net.ipv4.tcp_adv_win_scale = 2

# --- RFC1337: protect against spurious RST on TIME-WAIT ---
net.ipv4.tcp_rfc1337 = 1
SYSCTL_EOF

    if sysctl --system >/tmp/antidpi_sysctl.log 2>&1; then
        log_ok "sysctl parameters applied ($SYSCTL_FILE)"
    else
        log_warn "sysctl --system reported issues; see /tmp/antidpi_sysctl.log"
    fi

    local current_cc
    current_cc=$(sysctl -n net.ipv4.tcp_congestion_control 2>/dev/null || echo "unknown")
    if [[ "$current_cc" == "bbr" ]]; then
        log_ok "BBR congestion control is active"
    else
        log_warn "BBR not active (current: $current_cc) - kernel module 'tcp_bbr' may need to be loaded"
        modprobe tcp_bbr 2>/dev/null && sysctl -w net.ipv4.tcp_congestion_control=bbr >/dev/null 2>&1
    fi
}

# ============================================================
#  2) NIC tuning (offload disable) + systemd persistence
# ============================================================
apply_nic_tuning() {
    local iface="$1"
    log_step "Tuning NIC offload settings on interface: $iface"

    if ! command -v ethtool >/dev/null 2>&1; then
        log_info "Installing ethtool..."
        apt-get update -qq >/dev/null 2>&1
        apt-get install -y ethtool >/dev/null 2>&1
    fi

    ethtool -K "$iface" tso off gso off gro off >/dev/null 2>&1
    if [[ $? -eq 0 ]]; then
        log_ok "Offloading (tso/gso/gro) disabled on $iface"
    else
        log_warn "Some offload features may not be supported on $iface (non-fatal)"
    fi

    log_info "Creating persistence service: antidpi-nic.service"
    cat > "$NIC_SERVICE" << EOF
[Unit]
Description=Anti-DPI NIC offload persistence
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
ExecStart=/sbin/ethtool -K ${iface} tso off gso off gro off
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
EOF

    systemctl daemon-reload
    systemctl enable antidpi-nic.service >/dev/null 2>&1
    systemctl restart antidpi-nic.service >/dev/null 2>&1
    log_ok "antidpi-nic.service enabled and started"

    mkdir -p "$STATE_DIR"
    echo "$iface" > "$STATE_IFACE_FILE"
}

# ============================================================
#  3) MSS clamping via iptables
# ============================================================
apply_mss_clamp() {
    log_step "Applying TCP MSS clamping (packet fragmentation resistance)..."

    if ! command -v iptables >/dev/null 2>&1; then
        apt-get update -qq >/dev/null 2>&1
        apt-get install -y iptables >/dev/null 2>&1
    fi

    iptables -C FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --set-mss 500 2>/dev/null || \
        iptables -A FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --set-mss 500

    iptables -C OUTPUT -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --set-mss 500 2>/dev/null || \
        iptables -A OUTPUT -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --set-mss 500

    log_ok "MSS clamped to 500 bytes on FORWARD/OUTPUT chains"
}

# ============================================================
#  4) Traffic shaping / jitter via tc
# ============================================================
apply_traffic_shaping() {
    local iface="$1"
    log_step "Applying traffic shaping (jitter) on interface: $iface"

    if ! command -v tc >/dev/null 2>&1; then
        apt-get update -qq >/dev/null 2>&1
        apt-get install -y iproute2 >/dev/null 2>&1
    fi

    tc qdisc del dev "$iface" root >/dev/null 2>&1

    tc qdisc add dev "$iface" root handle 1: prio
    tc qdisc add dev "$iface" parent 1:3 handle 30: netem delay 10ms 4ms distribution normal

    tc filter add dev "$iface" protocol ip parent 1:0 prio 3 u32 \
        match ip sport 80 0xffff flowid 1:3

    if [[ $? -eq 0 ]]; then
        log_ok "Jitter (10ms +/- 4ms) applied to port 80 traffic on $iface"
    else
        log_warn "tc filter setup reported an issue (non-fatal, check 'tc qdisc show dev $iface')"
    fi
}

# ============================================================
#  5) Active probing defense: Nginx decoy + iptables redirect
# ============================================================
apply_probing_defense() {
    log_step "Setting up active-probing defense (Nginx decoy + iptables redirect)..."

    log_info "Installing nginx and iptables-persistent..."
    apt-get update -qq >/dev/null 2>&1
    DEBIAN_FRONTEND=noninteractive apt-get install -y nginx iptables-persistent >/dev/null 2>&1

    mkdir -p /var/www/antidpi/video/stream

    # A small valid-looking MP4 header so the response isn't an obviously empty file
    printf '\x00\x00\x00\x18ftypmp42\x00\x00\x00\x00mp42isom' > /var/www/antidpi/video/stream/live.mp4

    cat > "$NGINX_CONF" << 'NGINX_EOF'
server {
    listen 8080;
    server_name _;

    location /video/stream/live.mp4 {
        root /var/www/antidpi;
        default_type video/mp4;
        add_header Content-Disposition "inline";
        add_header Cache-Control "no-cache";
    }

    location / {
        return 200 "OK\n";
        default_type text/plain;
    }
}
NGINX_EOF

    if nginx -t >/tmp/antidpi_nginx.log 2>&1; then
        systemctl restart nginx
        systemctl enable nginx >/dev/null 2>&1
        log_ok "Nginx decoy listening on 127.0.0.1:8080"
    else
        log_err "Nginx config test failed; see /tmp/antidpi_nginx.log"
        return 1
    fi

    log_info "Configuring iptables NAT redirection rules for port 80..."
    iptables -t nat -C PREROUTING -p tcp --dport 80 -m string --string "GET /video/stream/live.mp4" --algo bm -j ACCEPT 2>/dev/null || \
        iptables -t nat -A PREROUTING -p tcp --dport 80 -m string --string "GET /video/stream/live.mp4" --algo bm -j ACCEPT

    iptables -t nat -C PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 8080 2>/dev/null || \
        iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 8080

    netfilter-persistent save >/dev/null 2>&1
    log_ok "iptables NAT rules applied and saved persistently"
}

# ============================================================
#  Full apply flow (menu option 1)
# ============================================================
run_full_optimization() {
    check_root
    log_step "Starting full anti-DPI optimization..."
    local iface
    iface=$(detect_iface)
    log_info "Detected primary interface: $iface"
    echo

    install_global_command
    echo
    apply_kernel_tweaks
    echo
    apply_nic_tuning "$iface"
    echo
    apply_mss_clamp
    echo
    apply_traffic_shaping "$iface"
    echo
    apply_probing_defense
    echo
    log_ok "All optimizations applied successfully."
    echo -e "${GREEN}${BOLD}Done. Run 'anti-dpi' anytime to reopen this menu.${NC}"
}

# ============================================================
#  Status check (menu option 2)
# ============================================================
check_status() {
    check_root
    log_step "System & Firewall Status"
    echo

    echo -e "${BOLD}-- Congestion Control --${NC}"
    local cc
    cc=$(sysctl -n net.ipv4.tcp_congestion_control 2>/dev/null || echo "unavailable")
    if [[ "$cc" == "bbr" ]]; then
        log_ok "BBR: active"
    else
        log_warn "BBR: NOT active (current: $cc)"
    fi
    echo

    echo -e "${BOLD}-- sysctl config file --${NC}"
    if [[ -f "$SYSCTL_FILE" ]]; then
        log_ok "$SYSCTL_FILE exists"
    else
        log_warn "$SYSCTL_FILE not found"
    fi
    echo

    echo -e "${BOLD}-- NIC offload / systemd service --${NC}"
    if systemctl is-enabled antidpi-nic.service >/dev/null 2>&1; then
        log_ok "antidpi-nic.service is enabled"
        systemctl is-active antidpi-nic.service >/dev/null 2>&1 && log_ok "antidpi-nic.service is active" || log_warn "antidpi-nic.service is not currently active"
    else
        log_warn "antidpi-nic.service not installed"
    fi
    if [[ -f "$STATE_IFACE_FILE" ]]; then
        local iface
        iface=$(cat "$STATE_IFACE_FILE")
        log_info "Tracked interface: $iface"
        ethtool -k "$iface" 2>/dev/null | grep -E "tcp-segmentation-offload|generic-segmentation-offload|generic-receive-offload"
    fi
    echo

    echo -e "${BOLD}-- iptables rules --${NC}"
    if iptables -S FORWARD 2>/dev/null | grep -q "TCPMSS"; then
        log_ok "MSS clamping rule present (FORWARD)"
    else
        log_warn "MSS clamping rule not found (FORWARD)"
    fi
    if iptables -t nat -S PREROUTING 2>/dev/null | grep -q "REDIRECT"; then
        log_ok "Port 80 -> 8080 redirect rule present"
    else
        log_warn "Port 80 redirect rule not found"
    fi
    echo

    echo -e "${BOLD}-- tc / traffic shaping --${NC}"
    if [[ -f "$STATE_IFACE_FILE" ]]; then
        local iface
        iface=$(cat "$STATE_IFACE_FILE")
        if tc qdisc show dev "$iface" 2>/dev/null | grep -q "netem"; then
            log_ok "Jitter shaping active on $iface"
        else
            log_warn "No jitter shaping found on $iface"
        fi
    fi
    echo

    echo -e "${BOLD}-- Nginx decoy --${NC}"
    if systemctl is-active nginx >/dev/null 2>&1; then
        log_ok "nginx is running"
        [[ -f "$NGINX_CONF" ]] && log_ok "$NGINX_CONF present" || log_warn "$NGINX_CONF missing"
    else
        log_warn "nginx is not running"
    fi
    echo

    echo -e "${BOLD}-- Global command --${NC}"
    if command -v anti-dpi >/dev/null 2>&1; then
        log_ok "'anti-dpi' command available at: $(command -v anti-dpi)"
    else
        log_warn "'anti-dpi' global command not found on PATH"
    fi
}

# ============================================================
#  Uninstall / rollback (menu option 3)
# ============================================================
run_uninstall() {
    check_root
    log_step "Rolling back all changes to default settings..."
    echo

    log_info "Removing sysctl config..."
    rm -f "$SYSCTL_FILE"
    sysctl --system >/dev/null 2>&1
    log_ok "sysctl reset"

    log_info "Removing NIC persistence service..."
    if [[ -f "$NIC_SERVICE" ]]; then
        systemctl stop antidpi-nic.service >/dev/null 2>&1
        systemctl disable antidpi-nic.service >/dev/null 2>&1
        rm -f "$NIC_SERVICE"
        systemctl daemon-reload
        log_ok "antidpi-nic.service removed"
    else
        log_info "No NIC service found, skipping."
    fi

    if [[ -f "$STATE_IFACE_FILE" ]]; then
        local iface
        iface=$(cat "$STATE_IFACE_FILE")
        log_info "Re-enabling offload features on $iface..."
        ethtool -K "$iface" tso on gso on gro on >/dev/null 2>&1
        log_info "Removing traffic shaping rules on $iface..."
        tc qdisc del dev "$iface" root >/dev/null 2>&1
    fi

    log_info "Removing iptables rules added by this script..."
    iptables -D FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --set-mss 500 2>/dev/null
    iptables -D OUTPUT -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --set-mss 500 2>/dev/null
    iptables -t nat -D PREROUTING -p tcp --dport 80 -m string --string "GET /video/stream/live.mp4" --algo bm -j ACCEPT 2>/dev/null
    iptables -t nat -D PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 8080 2>/dev/null
    if command -v netfilter-persistent >/dev/null 2>&1; then
        netfilter-persistent save >/dev/null 2>&1
    fi
    log_ok "iptables rules removed"

    log_info "Restoring Nginx configuration..."
    if [[ -f "$NGINX_CONF" ]]; then
        rm -f "$NGINX_CONF"
        rm -rf /var/www/antidpi
        nginx -t >/dev/null 2>&1 && systemctl restart nginx >/dev/null 2>&1
        log_ok "Nginx decoy site removed"
    else
        log_info "No Nginx decoy config found, skipping."
    fi

    log_info "Removing global command..."
    rm -f "$GLOBAL_CMD_A" "$GLOBAL_CMD_B" 2>/dev/null
    log_ok "'anti-dpi' global command removed"

    rm -rf "$STATE_DIR"

    echo
    echo -e "${GREEN}${BOLD}System successfully restored to factory/default network settings.${NC}"
}

# ============================================================
#  Main menu
# ============================================================
main_menu() {
    while true; do
        print_banner
        echo -e "${BOLD}Please choose an option:${NC}"
        echo -e "  ${CYAN}1)${NC} Apply Full Anti-DPI & OS Optimizations"
        echo -e "  ${CYAN}2)${NC} Check System & Firewall Status"
        echo -e "  ${CYAN}3)${NC} Uninstall & Restore Default Settings"
        echo -e "  ${CYAN}4)${NC} Exit"
        echo -e "${BLUE}------------------------------------------------------------${NC}"
        read -rp "$(echo -e "${BOLD}Select [1-4]: ${NC}")" choice
        echo

        case "$choice" in
            1) run_full_optimization ;;
            2) check_status ;;
            3) run_uninstall ;;
            4) echo -e "${GREEN}Goodbye.${NC}"; exit 0 ;;
            *) log_err "Invalid option." ;;
        esac

        echo
        read -rp "Press Enter to return to the menu..." _
    done
}

# ============================================================
#  Entry point
# ============================================================
check_root
main_menu
